#!/usr/bin/env python3
"""
HTML reporter module for generating HTML reports.
Дипломный проект - Автоматизированный веб-сканер
"""

import json
import datetime
import os
from typing import List, Dict, Any


class HTMLReporter:
    """Generates HTML reports for security scans."""
    
    def __init__(self, output_dir: str = "security_reports"):
        self.output_dir = output_dir
    
    def generate_html_report(self, 
                           vulnerabilities: List[Dict[str, Any]], 
                           filename: str = "security_report.html") -> str:
        """Generate HTML report."""
        os.makedirs(self.output_dir, exist_ok=True)
        
        filepath = f"{self.output_dir}/{filename}"
        
        # Создаем HTML контент
        html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Security Scan Report - Дипломный проект</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 40px; line-height: 1.6; }}
        h1 {{ color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }}
        h2 {{ color: #34495e; margin-top: 30px; }}
        .vulnerability {{ 
            border: 1px solid #ddd; 
            padding: 15px; 
            margin: 15px 0; 
            border-radius: 5px;
            background: #f9f9f9;
        }}
        .high {{ border-left: 5px solid #e74c3c; }}
        .medium {{ border-left: 5px solid #f39c12; }}
        .low {{ border-left: 5px solid #2ecc71; }}
        .severity {{ 
            display: inline-block; 
            padding: 3px 8px; 
            border-radius: 3px; 
            font-weight: bold;
            font-size: 0.9em;
        }}
        .severity-high {{ background: #e74c3c; color: white; }}
        .severity-medium {{ background: #f39c12; color: white; }}
        .severity-low {{ background: #2ecc71; color: white; }}
        .summary {{ 
            background: #ecf0f1; 
            padding: 20px; 
            border-radius: 5px; 
            margin: 20px 0;
        }}
        table {{ width: 100%; border-collapse: collapse; margin: 20px 0; }}
        th, td {{ padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }}
        th {{ background: #3498db; color: white; }}
        tr:hover {{ background: #f5f5f5; }}
        .footer {{ 
            margin-top: 40px; 
            padding-top: 20px; 
            border-top: 1px solid #ddd; 
            color: #7f8c8d; 
            font-size: 0.9em;
        }}
    </style>
</head>
<body>
    <h1>🔒 Security Scan Report</h1>
    <p><strong>Дипломный проект:</strong> Автоматизированный веб-сканер уязвимостей</p>
    
    <div class="summary">
        <h2>📊 Scan Summary</h2>
        <p><strong>Scan Date:</strong> {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
        <p><strong>Total Vulnerabilities Found:</strong> <span style="font-size: 1.5em; font-weight: bold;">{len(vulnerabilities)}</span></p>
        
        <table>
            <tr>
                <th>Severity</th>
                <th>Count</th>
                <th>Percentage</th>
            </tr>
            {self._generate_severity_summary(vulnerabilities)}
        </table>
    </div>
    
    <h2>📋 Detailed Vulnerabilities</h2>
    {self._generate_vulnerabilities_html(vulnerabilities)}
    
    <div class="footer">
        <p>Generated by Automated Web Vulnerability Scanner</p>
        <p>Diploma Project - Information Security 2025</p>
        <p>This report is generated automatically. For any questions, contact the project administrator.</p>
    </div>
</body>
</html>"""
        
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(html_content)
        
        return filepath
    
    def _generate_severity_summary(self, vulnerabilities: List[Dict[str, Any]]) -> str:
        """Generate HTML table with severity summary."""
        counts = {"High": 0, "Medium": 0, "Low": 0}
        for vuln in vulnerabilities:
            severity = vuln.get('severity', 'Medium')
            if severity in counts:
                counts[severity] += 1
        
        total = len(vulnerabilities)
        if total == 0:
            return "<tr><td colspan='3'>No vulnerabilities found</td></tr>"
        
        rows = []
        for severity, count in counts.items():
            percentage = (count / total * 100) if total > 0 else 0
            rows.append(f"<tr><td>{severity}</td><td>{count}</td><td>{percentage:.1f}%</td></tr>")
        
        return "\n".join(rows)
    
    def _generate_vulnerabilities_html(self, vulnerabilities: List[Dict[str, Any]]) -> str:
        """Generate HTML for each vulnerability."""
        if not vulnerabilities:
            return "<p>✅ No vulnerabilities found during the scan.</p>"
        
        items = []
        for i, vuln in enumerate(vulnerabilities, 1):
            severity = vuln.get('severity', 'Medium')
            severity_class = f"severity-{severity.lower()}"
            
            items.append(f"""
            <div class="vulnerability {severity.lower()}">
                <h3>{i}. {vuln.get('title', 'Unknown Vulnerability')}</h3>
                <p><span class="severity {severity_class}">{severity}</span></p>
                <p><strong>Type:</strong> {vuln.get('type', 'Unknown')}</p>
                <p><strong>Description:</strong> {vuln.get('description', 'No description available')}</p>
                <p><strong>Location:</strong> {vuln.get('location', 'Unknown')}</p>
                <p><strong>Recommendation:</strong> {vuln.get('recommendation', 'No recommendation available')}</p>
                <p><strong>CWE ID:</strong> {vuln.get('cwe_id', 'N/A')}</p>
            </div>
            """)
        
        return "\n".join(items)
